In [2]:
import torch
print(torch.__version__)
print(torch.cuda.is_available())

2.0.1
False


# Tensor

## 初始化

In [3]:
import torch
import numpy as np

data = [[1, 2], [3, 4]]

np_array = np.array(data) # Create Numpy object by list
t= torch.tensor(data) # Create tensor object by list
tensor_from_np = torch.from_numpy(np_array) # Create tensor object by numpy

np_from_tensor = t.numpy() # Transform Tensor to numpy
listdata = tensor_from_np.tolist() # Transform Tensor to list

print(t, '\n', np_from_tensor, '\n', listdata)

tensor([[1, 2],
        [3, 4]]) 
 [[1 2]
 [3 4]] 
 [[1, 2], [3, 4]]


In [5]:
# 从另一个张量对象复制数据来初始化新的张量

tensor_data = t.clone() # 返回和t相同的tensor， 存在新的内存中
new_data = t.detach() # 返回与t相同的tensor，新对象和旧对象共用内存

ones_data = torch.ones_like(t) # 和t形状一致的全1张量
zeros_data = torch.zeros_like(t) # 和t形状一致的全0张量
rand_data = torch.rand_like(t, dtype=torch.float) # 和t形状一致的随机浮点数张量

## Attribute

In [6]:
tensor = torch.rand(3,4)

print(f"tensor shape: {tensor.shape}")
print(f"tensor type: {tensor.shape}")
print(f"tensor device: {tensor.device}")

tensor shape: torch.Size([3, 4])
tensor type: torch.Size([3, 4])
tensor device: cpu


In [7]:
device = "cuda" if torch.cuda.is_available() else "cpu" # Can cuda boost?
print(device)

tensor = tensor.to(device) # put tensor to GPU
print(f"tensor device: {tensor.device}")

cpu
tensor device: cpu


## Slice & Index

In [8]:
tensor = torch.randint(1, 100, (4,4)) #(low, high, size)

print(f"1st line: {tensor[0]}")
print(f"1st column: {tensor[:,0]}")
print(f"last column: {tensor[..., -1]}") #... is same to :
tensor[:, 1] = 0 # replace the second column to 0
print(tensor)

1st line: tensor([44, 79, 47,  8])
1st column: tensor([44, 84,  3, 83])
last column: tensor([ 8, 90, 79,  4])
tensor([[44,  0, 47,  8],
        [84,  0, 31, 90],
        [ 3,  0, 49, 79],
        [83,  0, 63,  4]])


## Cat

除了要连接的维度值不同，其他维度的值应保持一致，否则不可以进行连接。

In [10]:
tensor1 = torch.randint(1,100,(4, 4))
tensor2 = torch.rand(3,4) 
tensor3 = torch.rand(4,2) 

t1 = torch.cat([tensor1, tensor2], dim=0) # 纵向连接
t2 = torch.cat([tensor1, tensor3], dim=1) # 横向连接 ()[]都行
print(tensor1.shape, tensor2.shape, tensor3.shape, t1.shape, t2.shape)

torch.Size([4, 4]) torch.Size([3, 4]) torch.Size([4, 2]) torch.Size([7, 4]) torch.Size([4, 6])


In [9]:
# stack 各个维度都应该一致

tensor1 = torch.randint(1,100,(2,4))
tensor2 = torch.zeros(2,4)
tensor3 = torch.ones(2,4)

t1 = torch.stack([tensor1, tensor2, tensor3],dim=0)
t2 = torch.stack([tensor1, tensor2, tensor3],dim=1)
t3 = torch.stack([tensor1, tensor2, tensor3],dim=2)
print(tensor1.shape, tensor2.shape, tensor3.shape, t1.shape, t2.shape, t3.shape)
t1,t2,t3

torch.Size([2, 4]) torch.Size([2, 4]) torch.Size([2, 4]) torch.Size([3, 2, 4]) torch.Size([2, 3, 4]) torch.Size([2, 4, 3])


(tensor([[[47.,  4., 45.,  3.],
          [59., 53., 95., 77.]],
 
         [[ 0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.]],
 
         [[ 1.,  1.,  1.,  1.],
          [ 1.,  1.,  1.,  1.]]]),
 tensor([[[47.,  4., 45.,  3.],
          [ 0.,  0.,  0.,  0.],
          [ 1.,  1.,  1.,  1.]],
 
         [[59., 53., 95., 77.],
          [ 0.,  0.,  0.,  0.],
          [ 1.,  1.,  1.,  1.]]]),
 tensor([[[47.,  0.,  1.],
          [ 4.,  0.,  1.],
          [45.,  0.,  1.],
          [ 3.,  0.,  1.]],
 
         [[59.,  0.,  1.],
          [53.,  0.,  1.],
          [95.,  0.,  1.],
          [77.,  0.,  1.]]]))

## Calculation

In [12]:
tensor1 = torch.randint(1,100,(2,4))
tensor2 = torch.ones(2,4)

# + 以下123是一样的
t_add1 = tensor1 + tensor2
t_add2 = tensor1.add(tensor2)
t_add3 = torch.add(tensor1, tensor2)

# 456是一样的，张量所有元素都加3，得到新的张量，原张量未改变
t_add4 = tensor1 +3
t_add5 = tensor1.add(3)
t_add6 = torch.add(tensor1, 3)

t_add7 = tensor1.add_(3) # 张量所有元素都加3，原张量tensor1也被修改

In [15]:
# -
t_sub1 = tensor1 - tensor2
t_sub2 = tensor1.sub(tensor2)
t_sub3 = torch.sub(tensor1, tensor2)

# 张量乘法
t_matmul1 = tensor.float() @ tensor2.T # 单精度相乘
t_matmul2 = tensor1.matmul(tensor2.T.long()) #long相乘

# 按元素相乘
t_mul1 = tensor1 * 3
t_mul2 = tensor.mul(3)
t_mul3 = torch.mul(tensor1, 3)

# /
t_div1 = tensor1 / tensor2
t_div2 = tensor1.div(tensor2)
t_div3 = torch.div(tensor1, tensor2)

特殊运算函数

In [21]:
t1 = torch.randn((5)) # 1dim tensor
t2 = torch.ones((5)) # 1dim tensor
t3 = torch.randn((2,5)) # 2dim tensor
t4 = torch.ones((5,2)) # 2dim tensor

t_d1 = torch.dot(t1, t2) # 1dim 内积
t_d2 = torch.matmul(t1, t2) # same to dot
print(t_d1 == t_d2)

t_m1 = torch.mm(t3, t4) ## mm support 2dim mul
t_m2 = torch.matmul(t3, t4)
print(t_m1 == t_m2)

t_n1 = torch.matmul(t3, t1) # dim1 * dim2 dim1会扩展维度，结果会删掉扩展的维度
print(t_n1.shape)

t_n2 = torch.matmul(t3, t1.view(5,1)).T # 手动扩展进行计算
print(t_n1 == t_n2)

tensor(True)
tensor([[True, True],
        [True, True]])
torch.Size([2])
tensor([[True, True]])


In [22]:
# 取张量的某个元素进行普通数据类型的运算 用item()

tensor = torch.randperm(10)
sum = tensor.sum()
sum_item = sum.item()

print(tensor)
print(sum, type(sum))
print(sum_item, type(sum_item))

tensor([9, 4, 7, 8, 5, 3, 2, 6, 0, 1])
tensor(45) <class 'torch.Tensor'>
45 <class 'int'>


# Autograd

设x和y是真实数据，z为模型预测值，设z = w * x + b，则w和b是模型需要优化的参数，通过loss损失可根据梯度下降法来优化w和b。

In [25]:
import torch
from torch.nn.functional import binary_cross_entropy_with_logits

x = torch.ones(5)
y = torch.zeros(3)
w = torch.randn(5, 3, requires_grad=True) # (shape=5*3, 梯度计算True)
b = torch.randn(3, requires_grad=True)
z = torch.matmul(x,w) + b

loss = binary_cross_entropy_with_logits(z, y) # 计算损失根据loss来优化网络参数
loss.backward() # 损失反向传播进行自动求导，得到参数梯度

print(w.grad) # 输出w的梯度，存储在w的grad属性中，grad属性也是张量
print(b.grad)

tensor([[0.2385, 0.2310, 0.2653],
        [0.2385, 0.2310, 0.2653],
        [0.2385, 0.2310, 0.2653],
        [0.2385, 0.2310, 0.2653],
        [0.2385, 0.2310, 0.2653]])
tensor([0.2385, 0.2310, 0.2653])


之后就可以利用学习率进行修正

默认情况下，所有张量的requires_grad属性被设置为True，表示都在跟踪梯度历史，以下是禁用跟踪

In [27]:
z = torch.matmul(x, w) + b
print(z.requires_grad)

# 禁用跟踪
with torch.no_grad():
    z = z = torch.matmul(x, w) + b
print(z.requires_grad)


# 也可以用这个
z_det = z.detach()
print(z_det.requires_grad)

True
False
False
